# Generated by Django 4.1.1 on 2022-09-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantshop', '0006_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cartQty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
